Add mutt setup

diff --git a/bin/mail-sync b/bin/mail-sync
--- a/bin/mail-sync
+++ b/bin/mail-sync
@@ -1,51 +1,106 @@
 #!/usr/bin/env bash
 
-#
-# Usage:
-# ./mail-sync [account]
-#
-# If account is ommitted, all accounts will be synced. If account is specified,
-# only the specified account will be synced.
-#
-# Afterward, all mail will be indexed and the argos indicators will be updated.
-#
+set -Eeuo pipefail
+trap cleanup SIGINT SIGTERM ERR EXIT
+
+script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
+
+usage() {
+  cat <<EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-a account]
+
+If account is omitted, all accounts will be synced. If account is specified,
+only the specified account will be synced.
+
+Afterward, all mail will be indexed.
+
+Available options:
+
+-h, --help      Print this help and exit
+-a, --account   Specify sync for a single account
+EOF
+  exit
+}
+
+clear_lock() {
+  [ -e ~/.mail-sync.lock ] && rm ~/.mail-sync.lock
+}
+
+cleanup() {
+  trap - SIGINT SIGTERM ERR EXIT
+  clear_lock
+}
+
+msg() {
+  echo >&2 -e "${1-}"
+}
+
+die() {
+  local msg=$1
+  local code=${2-1} # default exit status 1
+  msg "$msg"
+  exit "$code"
+}
+
+parse_params() {
+  account='all'
+
+  while :; do
+    case "${1-}" in
+    -h | --help) usage ;;
+    -a | --account)
+      account="${2-}"
+      shift
+      ;;
+    -?*) die "Unknown option: $1" ;;
+    *) break ;;
+    esac
+    shift
+  done
+
+  args=("$@")
+
+  return 0
+}
+
+parse_params "$@"
+
+MAIL_DIR="$HOME/Mail"
+LOG="$MAIL_DIR/mail-sync.log"
+
+# Log all output.
+exec &> >(while read line; do echo "[$(date)] $line" | tee -a "$LOG"; done)
 
 # Ensure there's an internet connection.
-if ! ~/bin/check-connection; then
-  echo "No internet connection available. Skipping sync."
-  sleep 1
-  exit 0
+if ! check-connection; then
+  die "No internet connection available. Skipping sync."
 fi
 
 # Acquire a lock.
-[ -f ~/.mail-sync.lock ] && echo "Another sync is already running." && sleep 1 && exit 0
+[ -e ~/.mail-sync.lock ] && die "Another sync is already running."
 touch ~/.mail-sync.lock
 
-# Send any queued email.
-~/bin/msmtpq-flush
+# Send any queued email. || true so that it doesn't cause this script to exit
+# if there isn't any queued mail to send.
+~/bin/msmtpq-flush || true
 
 # Ensure individual account maildirs exist.
-[ -d ~/.cache/mail ] || mkdir ~/.cache/mail
-[ -d ~/.cache/mail/Gmail ] || mkdir ~/.cache/mail/Gmail
-[ -d ~/.cache/mail/Personal ] || mkdir ~/.cache/mail/Personal
-[ -d ~/.cache/mail/Digitaldeployment ] || mkdir ~/.cache/mail/Digitaldeployment
-[ -d ~/.cache/mail/Pineconegrove ] || mkdir ~/.cache/mail/Pineconegrove
-[ -d ~/.cache/mail/Netherwire ] || mkdir ~/.cache/mail/Netherwire
-[ -d ~/.cache/mail/Eagansfoundation ] || mkdir ~/.cache/mail/Eagansfoundation
+[ -d ~/Mail ] || mkdir ~/Mail
+[ -d ~/Mail/Gmail ] || mkdir ~/Mail/Gmail
+[ -d ~/Mail/Personal ] || mkdir ~/Mail/Personal
+[ -d ~/Mail/Agilesix ] || mkdir ~/Mail/Agilesix
+[ -d ~/Mail/Digitaldeployment ] || mkdir ~/Mail/Digitaldeployment
+[ -d ~/Mail/Pineconegrove ] || mkdir ~/Mail/Pineconegrove
+[ -d ~/Mail/Netherwire ] || mkdir ~/Mail/Netherwire
+[ -d ~/Mail/Eagansfoundation ] || mkdir ~/Mail/Eagansfoundation
 
 # Sync everything if an account wasn't specified. Otherwise, sync the specified account.
-if [ -z ${1+x} ]; then
+if [ "$account" = "all" ]; then
     mbsync --all --verbose
 else
-    mbsync --verbose $1
+    mbsync --verbose $account
 fi
 
 # Index all the mail.
-mu index --maildir ~/.cache/mail
-
-# Update the menu bar display.
-touch ~/.config/argos/maildir.sh
-
-# Clear the lock.
-rm ~/.mail-sync.lock
+mu index
 
diff --git a/bin/msmtpq-flush b/bin/msmtpq-flush
--- a/bin/msmtpq-flush
+++ b/bin/msmtpq-flush
@@ -1,72 +1,124 @@
-#!/bin/bash
-set -e
-set -o pipefail
-shopt -s nullglob
+#!/usr/bin/env bash
 
-CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/msmtp/config"
-QUEUE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/mail.queue"
-LOG="${XDG_LOG_HOME:-$HOME/.local/log}/msmtp.log"
+set -Eeuo pipefail
+trap cleanup SIGINT SIGTERM ERR EXIT
 
-exec {stdout}>&1
-coproc logger {(while read line; do echo "$(date -Iseconds) $line"; done >>"$LOG";); }
-exec >&${logger[1]} 2>&1
+script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
 
-lock() {
-    local lock_fd
-    local path="${!#}"
-    exec {lock_fd}<"$path"
-    flock "$lock_fd"
+usage() {
+  cat <<EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-f]
+
+Sends all queued outgoing messages via msmtp.
+
+Available options:
+
+-h, --help      Print this help and exit
+-f, --force     Force queue processing, even if there is a stale lock.
+EOF
+  exit
+}
+
+clear_lock() {
+  [ -e ~/.msmtpq-flush.lock ] && rm ~/.msmtpq-flush.lock
+}
+
+cleanup() {
+  trap - SIGINT SIGTERM ERR EXIT
+  clear_lock
 }
 
 msg() {
-    echo "$(date -Iseconds) $1" >&$stdout
+  echo >&2 -e "${1-}"
 }
 
-[[ -d "$QUEUE_DIR" ]] || mkdir -m0700 -p "$QUEUE_DIR"
+die() {
+  local msg=$1
+  local code=${2-1} # default exit status 1
+  msg "$msg"
+  exit "$code"
+}
+
+parse_params() {
+  # default values of variables set from params
+  force=0
+  param=''
+
+  while :; do
+    case "${1-}" in
+    -h | --help) usage ;;
+    -f | --force) clear_lock ;;
+    -?*) die "Unknown option: $1" ;;
+    *) break ;;
+    esac
+    shift
+  done
+
+  args=("$@")
+
+  return 0
+}
+
+parse_params "$@"
+
+CONFIG="$HOME/.config/msmtp/config"
+MAIL_DIR="$HOME/Mail"
+QUEUE_DIR="$MAIL_DIR/Outbox"
+LOG="$MAIL_DIR/msmtpq.log"
+
+[[ -d "$MAIL_DIR" ]] || mkdir -p "$MAIL_DIR"
+[[ -d "$QUEUE_DIR" ]] || mkdir -p "$QUEUE_DIR"
+
+# Log all output.
+exec &> >(while read line; do echo "[$(date)] $line" | tee -a "$LOG"; done)
 
 if [[ ! -w "$QUEUE_DIR" ]]; then
-    echo "Insufficient privileges to write to queue."
-    exit 1
+    die "Insufficient privileges to modify queue."
 fi
 
-if ! lock -n -x "$QUEUE_DIR"; then
-    msg "Already running..."
-    exit 0
+if ! check-connection; then
+    die "No internet connection available. Skipping flush."
 fi
 
-if ! ping -qnc1 -w4 example.com >/dev/null 2>&1; then
-    echo "Not Online"
-    exit 0
+if [ -z "$(ls -A $QUEUE_DIR)" ]; then
+    die "No mail queued for delivery."
 fi
+
+if [ -f "~/.msmtpq-flush.lock" ]; then
+    die "msmtpq-flush is already running."
+fi
+
+# Acquire a lock
+touch ~/.msmtpq-flush.lock
 
 for mail in "$QUEUE_DIR"/*.mail/; do
     id="$(basename "$mail")"
     prefix="mail [ $id ]"
     if [[ ! -r "$mail/msmtp_flags" ]]; then
-        echo "$prefix failed to send message; missing flags"
+        msg "$prefix failed to send message; missing flags"
         continue
     fi
     if [[ ! -r "$mail/message" ]]; then
-        echo "$prefix failed to send message; missing message"
+        msg "$prefix failed to send message; missing message"
         continue
     fi
 
     if [[ ! -w "$mail" ]]; then
-        echo "$prefix failed to send message; insufficient privileges"
+        msg "$prefix failed to send message; insufficient privileges"
         continue
     fi
 
-    prefix="$prefix [ $(xargs -0 -a "$mail/msmtp_flags" printf '%s ')]"
+    prefix="$prefix [ $(gxargs -0 -a "$mail/msmtp_flags" printf '%s ')]"
 
-    echo "$prefix sending"
-    xargs -0 -a "$mail/msmtp_flags" msmtp -C "$CONFIG" -X - < "$mail/message"
+    msg "$prefix sending"
+    gxargs -0 -a "$mail/msmtp_flags" msmtp -C "$CONFIG" -X - < "$mail/message"
     ret="$?"
     if [[ ! "$ret" -eq 0 ]] ; then
-        echo "$prefix faild to send; msmtp rc = $ret"
+        msg "$prefix failed to send; msmtp rc = $ret"
         continue
     fi
     if ! rm -rf "$mail"; then
-        echo "$prefix sent but not purged from queue!?"
+        msg "$prefix sent but not purged from queue!?"
     fi
 done
 
